### ISSUE TITLE
DNN8

### ISSUE THREAD

**Issue by tdgarvey** [davidjrh/dnn.appinsights#2]
I get an exception on installing the extension with DNN 8. Don't think it is compatible.

`AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:2bc26a9a-2480-464b-a5b1-99a249ab71cc
AssemblyVersion:8.0.2
PortalId:0
UserId:2
TabId:36
RawUrl:/Host/Extensions/ctl/Install/rtab/36/portalid/0
Referrer:http://vsstoregraphics.thegarveygroup.com/Host/Extensions/ctl/Install/rtab/36/portalid/0
UserAgent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17
ExceptionHash:F5l4+80BPNNf+S9BfhzlGA==
Message:The system cannot find the file specified.
StackTrace:
InnerMessage:The system cannot find the file specified.
InnerStackTrace:
   at SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode)
   at SchwabenCode.QuickIO.QuickIOFile.OpenFileStream(QuickIOPathInfo pathInfo, FileAccess fileAccess, FileMode fileOption, FileShare shareMode, Int32 buffer)
   at SchwabenCode.QuickIO.QuickIOFile.OpenText(QuickIOPathInfo pathInfo)
   at DotNetNuke.Common.Utilities.FileSystemUtils.ReadFile(String filePath)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadTextFromFile(String source)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadManifest(XPathNavigator manifestNav)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller..ctor(String packageManifest, InstallerInfo info)
   at DotNetNuke.Services.Installer.Installer.ProcessPackages(XPathNavigator rootNav)
   at DotNetNuke.Services.Installer.Installer.ReadManifest(Stream stream)
   at DotNetNuke.Services.Installer.Installer.ReadManifest(Boolean deleteTemp)
   at DotNetNuke.Modules.Admin.Extensions.Install.wizInstall_NextButtonClick(Object sender, WizardNavigationEventArgs e)
   at System.Web.UI.WebControls.Wizard.OnNextButtonClick(WizardNavigationEventArgs e)
   at System.Web.UI.WebControls.Wizard.OnBubbleEvent(Object source, EventArgs e)
   at System.Web.UI.WebControls.Wizard.WizardChildTable.OnBubbleEvent(Object source, EventArgs args)
   at System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args)
   at System.Web.UI.WebControls.LinkButton.OnCommand(CommandEventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.WebControls.LinkButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)`

**Comment by tdgarvey** [comment]
Turns out I was grabbing the wrong install file. Installed the extension, but after enabled it throws a runtime error. So still not sure if it's compatible with DNN8.

**Comment by bdukes** [comment]
@tdgarvey version 2 should work for DNN 8, version 3 only works on DNN 9.0.1 and higher
